DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=54402;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=54401;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=54367;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=54348;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=54299;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=54277;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=54276;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=54275;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=54274;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=54161;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=54143;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=54073;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=54020;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=54019;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=54015;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53986;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53952;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53914;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53910;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53901;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53876;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53875;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53872;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53795;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53793;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53791;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53786;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53732;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53729;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53723;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53695;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53694;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53648;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53642;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53640;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53639;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53635;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53631;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53619;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53617;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53616;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53585;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53575;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53545;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53529;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53494;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53492;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53490;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53488;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53485;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53474;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53435;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53433;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53395;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53393;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53244;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53237;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53231;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53224;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53223;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53222;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53209;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53206;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53188;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53187;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53186;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53185;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53178;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53167;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53158;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53154;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53141;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53140;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53134;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53130;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53129;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53128;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53127;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53121;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53120;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53119;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53116;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53115;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53102;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53096;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53095;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53094;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=52672;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=52659;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=52571;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=52558;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=52498;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=52409;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=47242;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=45979;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=42098;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=35592;
DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=15214;
-- shannox

DELETE FROM `creature_onkill_reputation` WHERE  `creature_id`=53691;


INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (54402, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (54401, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (54367, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (54348, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (54299, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (54277, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (54276, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (54275, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (54274, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (54161, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (54143, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (54073, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (54020, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (54019, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (54015, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53986, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53952, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53914, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53910, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53901, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53876, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53875, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53872, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53795, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53793, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53791, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53786, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53732, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53729, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53723, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53695, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53694, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53648, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53642, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53640, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53639, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53635, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53631, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53619, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53617, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53616, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53585, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53575, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53545, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53529, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53494, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53492, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53490, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53488, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53485, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53474, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53435, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53433, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53395, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53393, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53244, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53237, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53231, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53224, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53223, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53222, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53209, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53206, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53188, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53187, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53186, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53185, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53178, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53167, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53158, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53154, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53141, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53140, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53134, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53130, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53129, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53128, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53127, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53121, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53120, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53119, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53116, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53115, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53102, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53096, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53095, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53094, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (52672, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (52659, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (52571, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (52558, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (52498, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (52409, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (47242, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (45979, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (42098, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (35592, 1204, 5, 30);
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (15214, 1204, 5, 30);
-- shannox
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `MaxStanding1`, `RewOnKillRepValue1`) VALUES (53691, 1204, 7, 250);