INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (1490, 'spell_warl_curse_of_the_elements');
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES (702, -85547, 1, 'Warlock Jinx rank 1: Weakness removes jinx');
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES (18223, -85547, 1, 'Warlock Jinx rank 1: Exhaustion removes jinx');
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES (1714, -85547, 1, 'Warlock Jinx rank 1: Tongues removes jinx');
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES (702, -85547, 2, 'Warlock Jinx rank 1: cannot override the Weakness');
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES (18223, -85547, 2, 'Warlock Jinx rank 1: cannot override the Exhaustion');
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES (1714, -85547, 2, 'Warlock Jinx rank 1: cannot override the Tongues');
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES (702, -86105, 1, 'Warlock Jinx rank 2: Weakness removes jinx');
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES (18223, -86105, 1, 'Warlock Jinx rank 2: Exhaustion removes jinx');
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES (1714, -86105, 1, 'Warlock Jinx rank 2: Tongues removes jinx');
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES (702, -86105, 2, 'Warlock Jinx rank 2: cannot override the Weakness');
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES (18223, -86105, 2, 'Warlock Jinx rank 2: cannot override the Exhaustion');
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES (1714, -86105, 2, 'Warlock Jinx rank 2: cannot override the Tongues');
